### PR TITLE
Prepare release 2.2.0

### PR DESCRIPTION
**Pull request by usergenic**
Lots of goodies in 2.2.0!  (I updated the README per feedback in prior release PR https://github.com/Polymer/polymer-bundler/pull/571, @katejeffreys)

## 2.2.0 - 2017-06-28
- Fixed issue where bundles produced by shell strategy incorrectly included eager html imports of the shell. https://github.com/Polymer/polymer-bundler/issues/471
- Fixed the `--inline-scripts` and `--inline-css` options, previously inlining happened regardless of whether the options were actually set.  Important, if you use the `bin/polymer-bundler` CLI you must provide these options to inline scripts and css now.
- Fixed issue producing assetpath in application root. https://github.com/Polymer/polymer-bundler/issues/562
- Fixed issue where absolute paths were not handled properly. https://github.com/Polymer/polymer-bundler/issues/559
- Fixed issue where out-dir was essentially ignored for a single bundle case. https://github.com/Polymer/polymer-bundler/issues/560
- Fixed issue where, if a different version of polymer-analyzer was given to Bundler's constructor, it caused instanceof check failures and resulting in documents not being identified as documents; added more definitive error messaging for this scenario as stop-gap until we switch to a no instanceof version of polymer-analyzer interface.
 - [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by usergenic** [comment]
cc @freshp86

**Comment by usergenic** [comment]
cc @web-padawan

**Comment by freshp86** [comment]
@usergenic: Will there be a need for a new release once https://github.com/Polymer/polymer-analyzer/issues/697 is addressed?

**Comment by usergenic** [comment]
@freshp86 not 100% sure if package-lock.json will force the old locked version - After analyzer removes typescript an npm install should just get the latest polymer-analyzer version.  We may release a 2.2.1 anyway though

**Pull request merged**
