### PR TITLE
Added support to preserve important comments marked with `<!--! ... -->`

### PR DESCRIPTION
**Pull request by usergenic**
- Fixes https://github.com/Polymer/polymer-bundler/issues/545
 - [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by stramel** [comment]
LGTM

**Comment by usergenic** [comment]
To the reviewer: desire to include `<!--!` stems from the forms usage in html minifiers for comment preservation plus the form has no side-effects like `<!--#` directives, so is an inert option for users wishing to preserve some comments.

**Comment by usergenic** [comment]
kthx :)

**Comment by andreabioli** [comment]
Not even a quick workaround, just for the time being???

**Comment by stramel** [comment]
@andreabioli what are you asking about?

**Comment by andreabioli** [comment]
Sorry, wrong thread... I wanted to ask this question in this one, https://github.com/Polymer/polymer-cli/issues/779, but I jumped here... :-(
What can I do, now? May I move my request?
Sorry again...

**Comment by stramel** [comment]
@andreabioli No worries, I figured you accidentally posted in the wrong thread. Just post it over there :smile:

**Pull request merged**
